### PR TITLE
New command proposal.

### PR DESCRIPTION
**Pull request by ecliptic-moon**
This is the foundation for the new command I'm about to propose (rep command).

### CODE REVIEW

**Comment by whomhasfallen** [comment]
Briefly explain how and what this'll do?

**Comment by ecliptic-moon** [comment]
Well, I created a file called `rep.json` to store guild members who've already been repped and their current rep count, then I planned on adding one to that amount each time the rep command was used on them.

**Comment by ecliptic-moon** [comment]
I have a basic structure for how everything's going to work.

**Comment by whomhasfallen** [comment]
So, like this?
```
{
  "username#discrim":"4"   
}
```

**Comment by whomhasfallen** [comment]
4 indicating how much rep the user has.

**Comment by ecliptic-moon** [comment]
Yep.

**Comment by ecliptic-moon** [comment]
If you merge, I'll get to pushing the rep command straight away.

**Comment by whomhasfallen** [comment]
Ok.

**Pull request merged**
