### PR TITLE
Embed image commands.

### PR DESCRIPTION
**Pull request by whomhasfallen**
Finished embedding image (cat/dog) commands.

### CODE REVIEW

**Comment by whomhasfallen** [comment]
@TotallyTriggeredTigers @goddyCodes @Sodre177 Thoughts?

**Review by n1ghtc4t — APPROVED** [review]
gucci, i mean good

**Comment by n1ghtc4t** [comment]
you can merge now bye

**Review by Sodre177 — APPROVED** [review]
Looks good!

**Comment by whomhasfallen** [comment]
@TotallyTriggeredTigers Make sure you review these changes at some point in time.

**Pull request merged**
